import ContractorFinancePage from "@/components/ContractorFinancePage";
import type { ContractorPageContent } from "@/lib/contractor-finance";
import { createMetadata } from "@/lib/seo";

const content: ContractorPageContent = {
  path: "/s-corp-savings-calculator",
  title: "S-Corp Savings Calculator: Model the Full Tradeoff",
  metaTitle: "S-Corp Savings Calculator and Cost Guide",
  description: "Estimate potential S-corporation savings after reasonable salary, payroll taxes, state fees, payroll, accounting, and compliance costs.",
  intro: "An S-corporation election can change how an eligible business owner's compensation is exposed to employment taxes, but the useful question is net savings after salary and compliance—not distributions multiplied by a tax rate.",
  toolTitle: "S-corporation election planning model",
  toolDescription: "Compare a baseline self-employment-tax estimate with payroll taxes on entered owner salary after payroll, professional, and state costs.",
  toolInputs: [
    "Business profit before owner wages and payroll costs",
    "Supportable reasonable salary for the owner's services",
    "Employer and employee payroll-tax components",
    "Payroll service, bookkeeping, tax preparation, and legal costs",
    "State franchise taxes, entity fees, and payroll registrations",
    "Retirement and health-benefit consequences tied to W2 wages",
  ],
  toolOutput: "estimated tax difference, added annual costs, break-even profit, and net planning benefit under stated assumptions.",
  sections: [
    {
      heading: "What an S-corporation election changes",
      paragraphs: [
        "An S corporation is a federal tax classification available to qualifying corporations and eligible entities, including many LLCs that make a valid election. The entity generally files Form 1120-S, and income, deductions, and other tax items pass through to shareholders. The election does not erase income tax on business profit. Its commonly discussed employment-tax effect arises because shareholder-employees receive wages for services while qualifying remaining profit may be distributed without being treated as wages.",
        "That distinction is narrower than online savings claims often suggest. A shareholder who performs more than minor services is generally an employee of the corporation. The corporation must pay reasonable compensation before making non-wage distributions to that shareholder-employee. Wages require payroll withholding and employment-tax reporting. The IRS may reclassify purported distributions as wages when compensation is unreasonably low relative to the services performed.",
      ],
    },
    {
      heading: "Reasonable compensation is the central input",
      paragraphs: [
        "A savings estimate is only as credible as its salary assumption. The IRS points to the source of gross receipts and factors such as training, experience, duties, time devoted to the business, payments to other workers, comparable compensation, agreements, and the use of a formula. A service business whose revenue is generated mainly by the owner's labor may support a different wage-to-profit relationship than a business whose revenue comes substantially from employees, equipment, or capital.",
        "Reasonable salary is not simply the smallest number that produces a desired tax result, nor is it automatically a fixed percentage of profit. Document the role, hours, responsibilities, market compensation evidence, and how the amount was selected. Revisit the analysis when the owner's duties, revenue, staffing, or profitability changes. The salary also cannot exceed what the shareholder actually receives directly or indirectly from the corporation.",
      ],
      bullets: [
        "Owner's technical, sales, management, and administrative duties",
        "Hours and effort devoted to the business",
        "Comparable pay for similar work and responsibility",
        "Revenue generated by the owner versus employees, capital, or equipment",
        "Compensation agreements and consistency of payroll practices",
      ],
    },
    {
      heading: "Calculate gross savings before claiming net savings",
      paragraphs: [
        "A simplified gross comparison starts with business profit under the current treatment and compares employment taxes with the taxes associated with reasonable W2 wages under S-corporation treatment. The model must include both employee and employer payroll-tax components where applicable and respect annual wage limits and additional Medicare rules. It should not imply that all distributions are tax-free; pass-through income generally remains relevant to the shareholder's income-tax return.",
        "The initial difference is not the final benefit. The corporation may owe employer payroll taxes and unemployment taxes, while the employee side is withheld from wages. Cash flow is divided among payroll, tax deposits, business distributions, and estimated income-tax payments. A useful calculator shows who pays each amount and avoids presenting payroll withholding as a new tax when some comparable tax burden already existed under the prior structure.",
      ],
    },
    {
      heading: "Subtract the cost of operating the structure",
      paragraphs: [
        "S-corporation treatment creates recurring work: payroll processing, timely tax deposits, quarterly and annual payroll forms, a separate business tax return, shareholder basis tracking, bookkeeping discipline, and state compliance. Costs vary widely by state and provider. Some owners also need updated operating documents, accountable-plan administration, workers' compensation review, or help handling shareholder health insurance correctly.",
        "Include the value of the owner's administrative time as well as invoices from service providers. A theoretical employment-tax reduction can disappear when annual profit is modest or irregular. The election may still offer non-tax benefits for a particular business, but it should not be sold as savings when compliance costs exceed the modeled tax difference. Break-even analysis is therefore more useful than showing only a best-case annual number.",
      ],
    },
    {
      heading: "Consider benefits and retirement planning",
      paragraphs: [
        "Owner wages affect more than payroll taxes. Retirement-plan contributions may depend on W2 compensation, and S-corporation distributions are not earned income for retirement-plan contribution purposes. Setting wages artificially low may therefore reduce the compensation base available for certain contributions. Health-insurance treatment for shareholders owning more than two percent also has special reporting requirements that should be handled with professional guidance.",
        "The correct comparison should include the owner's actual goals. A business prioritizing retirement contributions, mortgage qualification, or consistent payroll records may evaluate salary differently from a business focused only on near-term cash. Tax planning is one part of capital allocation, not the sole objective. The election should support the operating reality of the company and the owner's broader financial plan.",
      ],
    },
    {
      heading: "Eligibility, timing, and state treatment matter",
      paragraphs: [
        "Not every entity or ownership arrangement qualifies for S status. Federal rules limit eligible shareholders, the number of shareholders, and stock structure. Elections are made using Form 2553 and are subject to timing requirements, although late-election relief may be available in some circumstances. Existing entities should also consider accounting, payroll setup, and the effective date before assuming a retroactive result.",
        "States do not all treat S corporations the same way. A state may recognize the federal election but impose franchise taxes, minimum fees, separate elections, payroll obligations, or entity-level taxes. Because this phase does not generate state-specific pages, the planning model must leave state costs as explicit user inputs. A federal-only estimate should never be labeled as total savings.",
      ],
    },
    {
      heading: "When the election deserves closer review",
      paragraphs: [
        "An S-corporation election becomes more plausible when the business has stable profit materially above supportable reasonable compensation and enough margin to absorb payroll and professional fees. It is less compelling when profit is inconsistent, nearly all revenue reflects the owner's labor, the owner needs to distribute almost every dollar, or state costs are high. Future hiring, benefit plans, ownership changes, and financing plans can also affect the decision.",
        "Use scenarios rather than a single forecast. Model a low-profit year, expected year, and strong year with the same defensible salary logic. Include startup and transition costs separately from recurring expenses. Then review the result with a tax professional who can evaluate eligibility, salary support, state rules, and filing consequences. The output should guide questions, not replace the election analysis.",
      ],
    },
  ],
  examples: [
    {
      title: "Profit only modestly exceeds salary",
      body: "A solo service business expects $95,000 of profit before owner wages. Comparable duties support a substantial salary, leaving a relatively small potential distribution. After payroll service, a separate return, bookkeeping, state fees, and employer payroll costs, the estimated net benefit is limited. The owner may decide that simplicity is more valuable until profit becomes consistently higher.",
    },
    {
      title: "Stable profit with documented owner role",
      body: "A mature business has stable profit, employees who generate part of its revenue, and documented market compensation for the owner's management and technical duties. After paying a supportable salary, meaningful profit remains. A scenario model subtracts payroll, accounting, and state costs and still shows a potential benefit, giving the owner and tax adviser a reasonable basis for deeper election analysis.",
    },
  ],
  faq: [
    { q: "How does an S corporation potentially save taxes?", a: "The commonly modeled benefit comes from paying reasonable W2 compensation subject to employment taxes while eligible remaining business profit may be distributed without wage treatment. Pass-through profit is not automatically free from income tax." },
    { q: "What is a reasonable S-corporation salary?", a: "It is compensation commensurate with services performed, evaluated using duties, experience, time, comparable pay, revenue sources, and other facts. It is not a universal percentage of profit." },
    { q: "Does an LLC need to become a corporation under state law?", a: "An eligible LLC can generally elect S-corporation tax treatment without changing its state-law form. The legal entity and federal tax classification are separate questions." },
    { q: "At what income does an S corporation make sense?", a: "There is no universal threshold. The relevant measure is stable profit above reasonable salary compared with payroll, accounting, state, and administrative costs." },
    { q: "Are S-corporation distributions tax-free?", a: "No. Distributions are not generally wages, but shareholders usually report pass-through tax items, and basis and distribution rules apply. The employment-tax distinction should not be described as complete tax exemption." },
    { q: "Can I make an S-corporation election retroactive?", a: "Election timing rules apply, and late-election relief may be available when requirements are satisfied. Do not assume retroactive treatment without confirming eligibility and filing procedure." },
  ],
  methodology: [
    "The calculator compares a baseline self-employment-tax estimate with employment taxes on user-entered owner salary. It uses 2026 Social Security limits, applies the statutory net-earnings adjustment, and subtracts entered payroll, professional, and state costs from the gross employment-tax difference.",
    "The result reports gross tax difference, added operating cost, and net planning benefit separately. It does not choose a reasonable salary, determine eligibility, model income tax on pass-through profit, or characterize distributions as exempt from income tax.",
  ],
  sources: [
    { name: "IRS: S corporation compensation and medical insurance issues", href: "https://www.irs.gov/businesses/small-businesses-self-employed/s-corporation-compensation-and-medical-insurance-issues", note: "Reasonable-compensation factors and shareholder rules" },
    { name: "IRS: S corporation employees, shareholders and corporate officers", href: "https://www.irs.gov/businesses/small-businesses-self-employed/s-corporation-employees-shareholders-and-corporate-officers", note: "Wage treatment for shareholder-employees" },
    { name: "IRS: About Form 2553", href: "https://www.irs.gov/forms-pubs/about-form-2553", note: "S-corporation election form and instructions" },
    { name: "IRS: Retirement plan FAQs for S corporations", href: "https://www.irs.gov/retirement-plans/retirement-plan-faqs-regarding-contributions-s-corporation", note: "W2 compensation and retirement contributions" },
    { name: "SSA: 2026 contribution and benefit base", href: "https://www.ssa.gov/oact/cola/cbb.html", note: "Official 2026 Social Security wage base" },
  ],
};

export const metadata = createMetadata({ title: content.metaTitle, description: content.description, path: content.path });

export default function Page() {
  return <ContractorFinancePage content={content} />;
}
